version: '3.7'
services:
  server-go:
    container_name: server-go
    build: 
      context: .
      dockerfile: dockerfile.server
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend:
    name: backend
