FROM golang:1.25-alpine

WORKDIR /app

COPY . .

RUN go mod download
RUN apk update && apk add bash && bash setup-env.sh docker
RUN go build -o run-app

EXPOSE 8080
ENV API_PORT=:8080

CMD [ "./run-app" ]